import os
from datetime import date, timedelta
from typing import Optional
from tavily import TavilyClient

WHITELIST_DOMAINS = [
    # Tier 1: Singapore government official domains
    "gov.sg",
    "police.gov.sg",
    "moh.gov.sg",
    "cpf.gov.sg",
    "mom.gov.sg",
    "moe.gov.sg",
    "mas.gov.sg",
    "mha.gov.sg",
    "mof.gov.sg",
    "population.gov.sg",
    "pofmaoffice.gov.sg",
    # Tier 2: Singapore mainstream media
    "channelnewsasia.com",
    "straitstimes.com",
    "businesstimes.com.sg",
    "sg.news.yahoo.com",
    "todayonline.com",
    "mothership.sg",
    "blackdot.sg",
]


def _tavily_client() -> TavilyClient:
    key = (os.environ.get("TAVILY_API_KEY") or "").strip()
    if not key:
        raise ValueError(
            "Missing environment variable TAVILY_API_KEY. Do not hardcode secrets in code; configure it in the shell or a .env file."
        )
    return TavilyClient(api_key=key)


def _parse_iso_date(value: Optional[str]) -> Optional[date]:
    raw = (value or "").strip()
    if not raw or raw.lower() == "null":
        return None
    try:
        return date.fromisoformat(raw)
    except ValueError:
        return None


def _normalize_date_filters(
    start_date: Optional[str],
    end_date: Optional[str],
    today: Optional[date] = None,
) -> tuple[Optional[str], Optional[str]]:
    """Return Tavily-compatible date filters without changing the claim event date."""
    today = today or date.today()
    start = _parse_iso_date(start_date)
    end = _parse_iso_date(end_date)

    if start and end and start > end:
        start, end = end, start

    if start and start > today:
        return None, None
    if end and end > today:
        end = today

    if start and end and start == end:
        start = start - timedelta(days=1)

    return (
        start.isoformat() if start else None,
        end.isoformat() if end else None,
    )


# ---------------- Tavily search ----------------
def tavily_search(
    query: str,
    search_depth: str = "advanced",  # Configurable search depth
    max_results: int = 3,
    time_range: Optional[str] = None,  # Optional time-range filter
    start_date: Optional[str] = None,  # Optional start date
    end_date: Optional[str] = None,  # Optional end date
) -> list[dict]:
    """
    Call the Tavily Search API and retrieve evidence restricted to the Singapore domain whitelist.

    Args:
        query: English search query generated by the upstream claim extraction module.
        search_depth: Search depth ("basic" | "advanced" | "fast" | "ultra-fast").
        time_range: Optional time-range filter ("day" | "week" | "month" | "year").
        start_date: Optional start date (YYYY-MM-DD) from temporal normalization.
        end_date: Optional end date (YYYY-MM-DD) from temporal normalization.
        max_results: Maximum number of results to return.

    Returns:
        A normalized evidence list. Each item includes title, url, content, score,
        start_date, end_date, and time_range.
    """
    params: dict = {
        "query": query,
        "search_depth": search_depth,
        "max_results": max_results,
        "include_domains": WHITELIST_DOMAINS,
        "country": "singapore",
        "include_answer": False,
        "include_raw_content": False,
    }

    if time_range:
        params["time_range"] = time_range
    search_start_date, search_end_date = _normalize_date_filters(start_date, end_date)
    if search_start_date:
        params["start_date"] = search_start_date
    if search_end_date:
        params["end_date"] = search_end_date

    response = _tavily_client().search(**params)

    results = []
    for r in response.get("results", []):
        results.append(
            {
                "title": r.get("title", ""),
                "url": r.get("url", ""),
                "content": r.get("content", ""),
                "score": r.get("score", 0.0),
                "start_date": search_start_date,
                "end_date": search_end_date,
                "time_range": time_range,
            }
        )

    return results


# ---------------------------------------------------------------------------
# Demo when run directly
# ---------------------------------------------------------------------------
if __name__ == "__main__":
    demo_queries = [
        {
            "query": "Singapore lockdown policy 2026",
            "search_depth": "advanced",
            "time_range": "month",
        }
        # {
        #     "query": "CPF withdrawal policy changes Singapore",
        #     "search_depth": "basic",
        #     "start_date": "2025-01-01",
        #     "end_date": "2026-02-27",
        # },
    ]

    for q in demo_queries:
        print(f"\n{'='*60}")
        print(f"Query: {q['query']}")
        print(f"{'='*60}")
        evidence = tavily_search(**q)
        for i, e in enumerate(evidence, 1):
            print(f"\n--- Evidence {i} (score: {e['score']:.4f}) ---")
            print(f"Title : {e['title']}")
            print(f"URL   : {e['url']}")
            print(f"Content: {e['content'][:200]}...")
        # Tavily does not return a publish time, so the query window is tracked
        # separately through start_date/end_date.
        if not evidence:
            print("No results found.")
